params:
  epochs : 30
  batch_size : 32
  no_classes : 10
  input_shape : [28,28]
  loss_functions : sparse_categorical_crossentropy
  metrices : accuracy




  artifacts:
    artifacts_dir: artifacts
    model_dr : model
    no_classes : 10
    plots_dir: plots
    checkpoint_dir : checkpoints
    optimizer : SGD
    validation_datasize : 5000

logs:
  logs_dir: logs_dir
  general_logs : general_logs
  tensorboard_logs: tensorboard_logs